import { readFile, stat } from 'node:fs/promises';
const root='https://textcompare.amosfot.in/';
const homepage={file:'dist/index.html',title:'Text Compare Online — Private Diff Checker | Private Text Compare',description:'Compare two texts online with line-by-line and word-level highlights. Runs locally in your browser—no uploads, account, or tracking.',canonical:root,image:root+'og/homepage.png',asset:'dist/og/homepage.png'};
const guides=[
{file:'dist/guides/compare-two-texts/index.html',title:'How to Compare Two Texts Online | Private Text Compare',description:'Learn how to compare an original and revised text, interpret added, removed and changed lines, and review word-level edits privately in your browser.',canonical:root+'guides/compare-two-texts/',image:root+'og/guides/compare-two-texts.png',asset:'dist/og/guides/compare-two-texts.png',breadcrumb:'How to compare two texts',sibling:'/guides/line-vs-word-diff/'},
{file:'dist/guides/line-vs-word-diff/index.html',title:"Line Diff vs Word Diff: What's the Difference? | Private Text Compare",description:'Understand line-level and word-level text differences, when each is useful, and how changed lines can contain more precise inline word highlights.',canonical:root+'guides/line-vs-word-diff/',image:root+'og/guides/line-vs-word-diff.png',asset:'dist/og/guides/line-vs-word-diff.png',breadcrumb:'Line diff vs word diff',sibling:'/guides/compare-two-texts/'}
];
const hub='https://tools.amosfot.in/';
const fail=m=>{throw new Error('SEO verification failed: '+m)},decode=s=>s.replaceAll('&amp;','&').replaceAll('&#39;',"'").replaceAll('&quot;','"'),has=(s,v,m)=>{if(!s.includes(v))fail(m)};
function hubLink(html,label){const href='href="'+hub+'"',count=html.split(href).length-1;if(count!==1)fail(label+' hub link count '+count);has(html,'<a href="'+hub+'">Amosfot Tools</a>',label+' hub anchor')}
async function htmlFor(file){return decode(await readFile(file,'utf8').catch(()=>fail(file+' missing')))}
function jsonNodes(html,label){const matches=[...html.matchAll(/<script[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)];if(matches.length!==1)fail(label+' JSON-LD count');const data=JSON.parse(matches[0][1]);return{data,nodes:data['@graph']||[data]}}
async function png(path,label){const bytes=await readFile(path).catch(()=>fail(label+' OG missing'));if(bytes.readUInt32BE(16)!==1200||bytes.readUInt32BE(20)!==630)fail(label+' OG dimensions')}
function common(html,p,label,type){has(html,'<title>'+p.title+'</title>',label+' title');has(html,'name="description" content="'+p.description+'"',label+' description');has(html,'rel="canonical" href="'+p.canonical+'"',label+' canonical');has(html,'name="robots" content="index, follow, max-image-preview:large"',label+' robots');for(const x of [['og:type',type],['og:site_name','Private Text Compare'],['og:title',p.title],['og:description',p.description],['og:url',p.canonical],['og:image',p.image],['og:image:width','1200'],['og:image:height','630']])has(html,'property="'+x[0]+'" content="'+x[1]+'"',label+' '+x[0]);has(html,'property="og:image:alt" content="',label+' og alt');for(const x of [['twitter:card','summary_large_image'],['twitter:title',p.title],['twitter:description',p.description],['twitter:image',p.image]])has(html,'name="'+x[0]+'" content="'+x[1]+'"',label+' '+x[0]);has(html,'name="twitter:image:alt" content="',label+' twitter alt');has(html,'href="/favicon.svg"',label+' favicon');if(/pages\.dev/i.test(html)||/noindex/i.test(html))fail(label+' preview metadata')}
const home=await htmlFor(homepage.file);common(home,homepage,'homepage','website');hubLink(home,'homepage');const hg=jsonNodes(home,'homepage');const w=hg.nodes.find(n=>n['@type']==='WebSite'),a=hg.nodes.find(n=>n['@type']==='WebApplication');if(!w||w.url!==root||w.name!=='Private Text Compare')fail('homepage WebSite');if(!a||a.url!==root||a.applicationCategory!=='UtilitiesApplication'||a.operatingSystem!=='Any'||a.isAccessibleForFree!==true)fail('homepage WebApplication');if(a.offers?.['@type']!=='Offer'||a.offers?.price!=='0'||a.offers?.priceCurrency!=='USD')fail('homepage Offer');if(hg.nodes.some(n=>n['@type']==='WebPage'))fail('homepage guide schema regression');for(const h of ['/guides/compare-two-texts/','/guides/line-vs-word-diff/'])has(home,'href="'+h+'"','homepage guide link');await png(homepage.asset,'homepage');
for(const g of guides){const html=await htmlFor(g.file);common(html,g,g.breadcrumb,'article');hubLink(html,g.breadcrumb);has(html,'href="/"',g.breadcrumb+' homepage link');has(html,'href="'+g.sibling+'"',g.breadcrumb+' sibling link');const graph=jsonNodes(html,g.breadcrumb);const types=graph.nodes.map(n=>n['@type']);if(types.length!==3||!types.includes('WebSite')||!types.includes('WebPage')||!types.includes('BreadcrumbList')||types.includes('WebApplication'))fail(g.breadcrumb+' graph types');const site=graph.nodes.find(n=>n['@type']==='WebSite'),page=graph.nodes.find(n=>n['@type']==='WebPage'),crumbs=graph.nodes.find(n=>n['@type']==='BreadcrumbList');if(!site||site['@id']!==root+'#website'||site.url!==root||site.name!=='Private Text Compare'||site.inLanguage!=='en')fail(g.breadcrumb+' WebSite');if(!page||page['@id']!==g.canonical+'#webpage'||page.url!==g.canonical||page.name!==g.breadcrumb||page.description!==g.description||page.inLanguage!=='en'||page.isPartOf?.['@id']!==root+'#website')fail(g.breadcrumb+' WebPage');const items=crumbs?.itemListElement;if(!Array.isArray(items)||items.length!==2||items[0]?.position!==1||items[0]?.name!=='Private Text Compare'||items[0]?.item!==root||items[1]?.position!==2||items[1]?.name!==g.breadcrumb||items[1]?.item!==g.canonical)fail(g.breadcrumb+' BreadcrumbList');if(/"aggregateRating"|"review"/.test(JSON.stringify(graph.data)))fail(g.breadcrumb+' fabricated trust data');await png(g.asset,g.breadcrumb)}
await stat('dist/favicon.svg').catch(()=>fail('favicon'));const robots=await readFile('dist/robots.txt','utf8').catch(()=>fail('robots'));has(robots,'Allow: /','robots allow');has(robots,'Sitemap: '+root+'sitemap.xml','robots sitemap');if(/pages\.dev/i.test(robots))fail('robots pages.dev');const sitemap=await readFile('dist/sitemap.xml','utf8').catch(()=>fail('sitemap'));const locations=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1]),expected=[root,root+'guides/compare-two-texts/',root+'guides/line-vs-word-diff/'];if(JSON.stringify(locations)!==JSON.stringify(expected))fail('sitemap exact locations '+JSON.stringify(locations));if(/pages\.dev|<lastmod>|<priority>|<changefreq>/i.test(sitemap))fail('sitemap disallowed metadata');console.log('SEO verification passed for Private Text Compare homepage and two guides.');
