import { readFile, stat } from 'node:fs/promises';
const e={title:'Text Compare Online — Private Diff Checker | Private Text Compare',description:'Compare two texts online with line-by-line and word-level highlights. Runs locally in your browser—no uploads, account, or tracking.',canonical:'https://textcompare.amosfot.in/',name:'Private Text Compare',image:'https://textcompare.amosfot.in/og/homepage.png',sitemap:'https://textcompare.amosfot.in/sitemap.xml',links:['https://upload-ready.amosfot.in/','https://pdf-ready.amosfot.in/']};
const fail=m=>{throw new Error('SEO verification failed: '+m)}; const has=(s,v,m)=>{if(!s.includes(v))fail(m)};
const html=await readFile('dist/index.html','utf8').catch(()=>fail('dist/index.html missing'));
has(html,'<title>'+e.title+'</title>','title');has(html,'name="description" content="'+e.description+'"','description');has(html,'rel="canonical" href="'+e.canonical+'"','canonical');has(html,'name="robots" content="index, follow, max-image-preview:large"','robots');
for(const x of [['og:type','website'],['og:site_name',e.name],['og:title',e.title],['og:description',e.description],['og:url',e.canonical],['og:image',e.image],['og:image:width','1200'],['og:image:height','630']])has(html,'property="'+x[0]+'" content="'+x[1]+'"',x[0]);
has(html,'property="og:image:alt" content="','og alt');for(const x of [['twitter:card','summary_large_image'],['twitter:title',e.title],['twitter:description',e.description],['twitter:image',e.image]])has(html,'name="'+x[0]+'" content="'+x[1]+'"',x[0]);has(html,'name="twitter:image:alt" content="','twitter alt');
if(/pages\.dev/i.test(html))fail('pages.dev in production HTML');if(/noindex/i.test(html))fail('noindex in production HTML');
const ms=[...html.matchAll(/<script[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)];if(!ms.length)fail('JSON-LD missing');let nodes=[];for(const m of ms){const j=JSON.parse(m[1]);nodes=nodes.concat(j['@graph']||[j]);}
const w=nodes.find(n=>n['@type']==='WebSite'),a=nodes.find(n=>n['@type']==='WebApplication');if(!w||w.url!==e.canonical||w.name!==e.name)fail('WebSite');if(!a||a.url!==e.canonical||a.name!==e.name)fail('WebApplication');
if(a.applicationCategory!=='UtilitiesApplication'||a.operatingSystem!=='Any'||a.isAccessibleForFree!==true)fail('app properties');if(a.offers?.['@type']!=='Offer'||a.offers?.price!=='0'||a.offers?.priceCurrency!=='USD')fail('free offer');if(/aggregateRating|"review"/.test(JSON.stringify(nodes)))fail('rating/review');
await stat('dist/favicon.svg').catch(()=>fail('favicon'));const png=await readFile('dist/og/homepage.png').catch(()=>fail('OG PNG'));if(png.readUInt32BE(16)!==1200||png.readUInt32BE(20)!==630)fail('OG dimensions');
const robots=await readFile('dist/robots.txt','utf8').catch(()=>fail('robots.txt'));has(robots,'Allow: /','robots allow');has(robots,'Sitemap: '+e.sitemap,'robots sitemap');if(/pages\.dev/i.test(robots))fail('robots pages.dev');
const sitemap=await readFile('dist/sitemap.xml','utf8').catch(()=>fail('sitemap'));has(sitemap,'<loc>'+e.canonical+'</loc>','sitemap canonical');if(/pages\.dev/i.test(sitemap))fail('sitemap pages.dev');for(const link of e.links)has(html,'href="'+link+'"','portfolio link '+link);
console.log('SEO verification passed for Private Text Compare.');
